# Generated by Django 5.1.4 on 2025-01-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_author_age_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
    ]
